### PR TITLE
Minor improvements in the `README.md` file

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Minor improvements in the `README.md` file.
  - All the changes are shown in the Git diff. If you have any questions about them, please let me know below. 🙂

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
Thanks a lot, looks great.

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@Panquesito7 This made the youtube icon super large, I think.

**Comment by KendallDoesCoding** [comment]
@Panquesito7 "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged." Please restore branch

**Comment by KendallDoesCoding** [comment]
@Panquesito7 I still can't revert the changes for some reason, can you fix the issue and make a new PR?

**Comment by Panquesito7** [comment]
> @Panquesito7 I still can't revert the changes for some reason, can you fix the issue and make a new PR?

Not sure. Try copying the old readme file from an older commit, make a branch, paste, commit, make a PR, then merge. Let me know if you need any help. 🙂

**Comment by KendallDoesCoding** [comment]
Will do.

**Comment by KendallDoesCoding** [comment]
@Panquesito7 Reverted changes, If you know how to make the YT icon small, please do that in the minor_improvements branch and make a new PR @Panquesito7

**Pull request merged**
